language: go

services:
  - docker

env:
  global:
    - ETHEREUM_JSONRPC_URL=http://localhost:8545

before_install:
  - docker run -d --rm -p 8545:8545 -p 8546:8546 --name zrx gcr.io/zaidan-eth-net/0x-snapshot:v3

go:
  - 1.13
  - master
